spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://mysql:3306/ms_product?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9090
  error:
    include-message: always

springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/v3/api-docs
  packages-to-scan: com.example.product

management:
  endpoints:
    web:
      exposure:
        include: "*"
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: debug
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

api:
  response-codes:
    ok:
      description: OK
    bad-request:
      description: Bad Request, invalid format of the request. See response message for more information
    internal-server:
      description: Internal Server Error. See response message for more information